FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-stretch-run

WORKDIR /project

# RUN useradd -m -r user && chown user /project

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

# USER user
CMD ["python","src/bot.py"]